export enum MessageType5Headers {
  Date = "Date",
  Repeat = "Repeat",
  MMSI = "MMSI",
  Packet = "Packet",
  Channel = "Channel",
  Country = "Country",
  Ais = "AIS",
  IMO = "IMO",
  CallSign = "Call Sign",
  Name = "Name",
  Type = "Type",
  ToBow = "To Bow [m]",
  ToStern = "To Stern [m]",
  ToPort = "To Port [m]",
  ToStarboard = "To Starboard [m]",
  EPFD = "EPFD",
  Month = "Month",
  Day = "Day",
  Hour = "Hour",
  Minute = "Minute",
  Draught = "Draught [m/10]",
  Destination = "Destination",
  Spare = "Spare",
  DTE = "DTE"
}
