export enum MessageType21Headers {
  Date = "Date",
  Repeat = "Repeat",
  MMSI = "MMSI",
  Packet = "Packet",
  Channel = "Channel",
  Country = "Country",
  Aid = "Aid",
  Name = "Name",
  Accuracy = "Accuracy",
  LON = "LON [deg]",
  LAT = "LAT [deg]",
  ToBow = "To Bow [m]",
  ToStern = "To Stern [m]",
  ToPort = "To Port [m]",
  ToStarboard= "To Starboard [m]",
  EPFD = "EPFD",
  Second = "Second",
  OffPosition = "OffPosition",
  Reserved = "Reserved",
  Spare = "Spare",
  RAIM = "RAIM",
  Virtual = "Flag",
  Assigned = "Assigned"
}
