export interface MessageType5 {
  id: number,
  date?: Date,
  messageType: string,
  repeat: number,
  mmsi: number,
  packet: string,
  channel: string,
  country: string,
  aisVersion: string,
  imoNumber: number,
  callSign: string,
  vesselName: string,
  shipType: string,
  dimensionToBow: number,
  dimensionToStern: number,
  dimensionToPort: number,
  dimensionToStarboard: number,
  epfd: string,
  month?: number,
  day?: number,
  hour?: number,
  minute?: number,
  draught: number,
  destination: string,
  spare: number,
  dte: string
}
